//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.19 at 03:03:19 PM EDT 
//


package com.github.redhatqe.polarize.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for testcase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testcase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="caseimportance">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required" type="{com.redhat.qe.rhsm.PolarizeTypes}imp-types" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="caselevel">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required" type="{com.redhat.qe.rhsm.PolarizeTypes}case-types" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="testtype">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required" type="{com.redhat.qe.rhsm.PolarizeTypes}test-types" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="caseposneg">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required" type="{com.redhat.qe.rhsm.PolarizeTypes}posneg-types" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="caseautomation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required" type="{com.redhat.qe.rhsm.PolarizeTypes}automation-types" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="status">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="requirements">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="requirement" type="{com.redhat.qe.rhsm.RequirementType}req-type" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="setup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="teststeps" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="teststep" type="{com.redhat.qe.rhsm.PolarizeTypes}teststep-type" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="teardown" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="project" use="required" type="{com.redhat.qe.rhsm.PolarizeTypes}project-vals" />
 *       &lt;attribute name="author" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="workitem-type" use="required" type="{com.redhat.qe.rhsm.PolarizeTypes}wi-types" />
 *       &lt;attribute name="hyperlink" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="workitem-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testcase", namespace = "com.redhat.qe.rhsm.TestCaseType", propOrder = {

})
public class Testcase {

    @XmlElement(namespace = "com.redhat.qe.rhsm.TestCaseType")
    protected String description;
    @XmlElement(namespace = "com.redhat.qe.rhsm.TestCaseType", required = true)
    protected String title;
    @XmlElement(namespace = "com.redhat.qe.rhsm.TestCaseType", required = true)
    protected Testcase.Caseimportance caseimportance;
    @XmlElement(namespace = "com.redhat.qe.rhsm.TestCaseType", required = true)
    protected Testcase.Caselevel caselevel;
    @XmlElement(namespace = "com.redhat.qe.rhsm.TestCaseType", required = true)
    protected Testcase.Testtype testtype;
    @XmlElement(namespace = "com.redhat.qe.rhsm.TestCaseType", required = true)
    protected Testcase.Caseposneg caseposneg;
    @XmlElement(namespace = "com.redhat.qe.rhsm.TestCaseType", required = true)
    protected Testcase.Caseautomation caseautomation;
    @XmlElement(namespace = "com.redhat.qe.rhsm.TestCaseType", required = true)
    protected Testcase.Status status;
    @XmlElement(namespace = "com.redhat.qe.rhsm.TestCaseType", required = true)
    protected Testcase.Requirements requirements;
    @XmlElement(namespace = "com.redhat.qe.rhsm.TestCaseType")
    protected String setup;
    @XmlElement(namespace = "com.redhat.qe.rhsm.TestCaseType")
    protected Testcase.Teststeps teststeps;
    @XmlElement(namespace = "com.redhat.qe.rhsm.TestCaseType")
    protected String teardown;
    @XmlAttribute(name = "project", required = true)
    protected ProjectVals project;
    @XmlAttribute(name = "author", required = true)
    protected String author;
    @XmlAttribute(name = "workitem-type", required = true)
    protected WiTypes workitemType;
    @XmlAttribute(name = "hyperlink")
    protected String hyperlink;
    @XmlAttribute(name = "workitem-id")
    protected String workitemId;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the caseimportance property.
     * 
     * @return
     *     possible object is
     *     {@link Testcase.Caseimportance }
     *     
     */
    public Testcase.Caseimportance getCaseimportance() {
        return caseimportance;
    }

    /**
     * Sets the value of the caseimportance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testcase.Caseimportance }
     *     
     */
    public void setCaseimportance(Testcase.Caseimportance value) {
        this.caseimportance = value;
    }

    /**
     * Gets the value of the caselevel property.
     * 
     * @return
     *     possible object is
     *     {@link Testcase.Caselevel }
     *     
     */
    public Testcase.Caselevel getCaselevel() {
        return caselevel;
    }

    /**
     * Sets the value of the caselevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testcase.Caselevel }
     *     
     */
    public void setCaselevel(Testcase.Caselevel value) {
        this.caselevel = value;
    }

    /**
     * Gets the value of the testtype property.
     * 
     * @return
     *     possible object is
     *     {@link Testcase.Testtype }
     *     
     */
    public Testcase.Testtype getTesttype() {
        return testtype;
    }

    /**
     * Sets the value of the testtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testcase.Testtype }
     *     
     */
    public void setTesttype(Testcase.Testtype value) {
        this.testtype = value;
    }

    /**
     * Gets the value of the caseposneg property.
     * 
     * @return
     *     possible object is
     *     {@link Testcase.Caseposneg }
     *     
     */
    public Testcase.Caseposneg getCaseposneg() {
        return caseposneg;
    }

    /**
     * Sets the value of the caseposneg property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testcase.Caseposneg }
     *     
     */
    public void setCaseposneg(Testcase.Caseposneg value) {
        this.caseposneg = value;
    }

    /**
     * Gets the value of the caseautomation property.
     * 
     * @return
     *     possible object is
     *     {@link Testcase.Caseautomation }
     *     
     */
    public Testcase.Caseautomation getCaseautomation() {
        return caseautomation;
    }

    /**
     * Sets the value of the caseautomation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testcase.Caseautomation }
     *     
     */
    public void setCaseautomation(Testcase.Caseautomation value) {
        this.caseautomation = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Testcase.Status }
     *     
     */
    public Testcase.Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testcase.Status }
     *     
     */
    public void setStatus(Testcase.Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the requirements property.
     * 
     * @return
     *     possible object is
     *     {@link Testcase.Requirements }
     *     
     */
    public Testcase.Requirements getRequirements() {
        return requirements;
    }

    /**
     * Sets the value of the requirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testcase.Requirements }
     *     
     */
    public void setRequirements(Testcase.Requirements value) {
        this.requirements = value;
    }

    /**
     * Gets the value of the setup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSetup() {
        return setup;
    }

    /**
     * Sets the value of the setup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSetup(String value) {
        this.setup = value;
    }

    /**
     * Gets the value of the teststeps property.
     * 
     * @return
     *     possible object is
     *     {@link Testcase.Teststeps }
     *     
     */
    public Testcase.Teststeps getTeststeps() {
        return teststeps;
    }

    /**
     * Sets the value of the teststeps property.
     * 
     * @param value
     *     allowed object is
     *     {@link Testcase.Teststeps }
     *     
     */
    public void setTeststeps(Testcase.Teststeps value) {
        this.teststeps = value;
    }

    /**
     * Gets the value of the teardown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeardown() {
        return teardown;
    }

    /**
     * Sets the value of the teardown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeardown(String value) {
        this.teardown = value;
    }

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectVals }
     *     
     */
    public ProjectVals getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectVals }
     *     
     */
    public void setProject(ProjectVals value) {
        this.project = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the workitemType property.
     * 
     * @return
     *     possible object is
     *     {@link WiTypes }
     *     
     */
    public WiTypes getWorkitemType() {
        return workitemType;
    }

    /**
     * Sets the value of the workitemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link WiTypes }
     *     
     */
    public void setWorkitemType(WiTypes value) {
        this.workitemType = value;
    }

    /**
     * Gets the value of the hyperlink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHyperlink() {
        return hyperlink;
    }

    /**
     * Sets the value of the hyperlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHyperlink(String value) {
        this.hyperlink = value;
    }

    /**
     * Gets the value of the workitemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkitemId() {
        return workitemId;
    }

    /**
     * Sets the value of the workitemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkitemId(String value) {
        this.workitemId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required" type="{com.redhat.qe.rhsm.PolarizeTypes}automation-types" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Caseautomation {

        @XmlAttribute(name = "value", required = true)
        protected AutomationTypes value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link AutomationTypes }
         *     
         */
        public AutomationTypes getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link AutomationTypes }
         *     
         */
        public void setValue(AutomationTypes value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required" type="{com.redhat.qe.rhsm.PolarizeTypes}imp-types" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Caseimportance {

        @XmlAttribute(name = "value", required = true)
        protected ImpTypes value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link ImpTypes }
         *     
         */
        public ImpTypes getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImpTypes }
         *     
         */
        public void setValue(ImpTypes value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required" type="{com.redhat.qe.rhsm.PolarizeTypes}case-types" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Caselevel {

        @XmlAttribute(name = "value", required = true)
        protected CaseTypes value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link CaseTypes }
         *     
         */
        public CaseTypes getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link CaseTypes }
         *     
         */
        public void setValue(CaseTypes value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required" type="{com.redhat.qe.rhsm.PolarizeTypes}posneg-types" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Caseposneg {

        @XmlAttribute(name = "value", required = true)
        protected PosnegTypes value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link PosnegTypes }
         *     
         */
        public PosnegTypes getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link PosnegTypes }
         *     
         */
        public void setValue(PosnegTypes value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="requirement" type="{com.redhat.qe.rhsm.RequirementType}req-type" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "requirement"
    })
    public static class Requirements {

        @XmlElement(namespace = "com.redhat.qe.rhsm.TestCaseType", required = true)
        protected List<ReqType> requirement;

        /**
         * Gets the value of the requirement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the requirement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRequirement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ReqType }
         * 
         * 
         */
        public List<ReqType> getRequirement() {
            if (requirement == null) {
                requirement = new ArrayList<ReqType>();
            }
            return this.requirement;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Status {

        @XmlAttribute(name = "value")
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="teststep" type="{com.redhat.qe.rhsm.PolarizeTypes}teststep-type" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "teststep"
    })
    public static class Teststeps {

        @XmlElement(namespace = "com.redhat.qe.rhsm.TestCaseType")
        protected TeststepType teststep;

        /**
         * Gets the value of the teststep property.
         * 
         * @return
         *     possible object is
         *     {@link TeststepType }
         *     
         */
        public TeststepType getTeststep() {
            return teststep;
        }

        /**
         * Sets the value of the teststep property.
         * 
         * @param value
         *     allowed object is
         *     {@link TeststepType }
         *     
         */
        public void setTeststep(TeststepType value) {
            this.teststep = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required" type="{com.redhat.qe.rhsm.PolarizeTypes}test-types" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Testtype {

        @XmlAttribute(name = "value", required = true)
        protected TestTypes value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link TestTypes }
         *     
         */
        public TestTypes getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link TestTypes }
         *     
         */
        public void setValue(TestTypes value) {
            this.value = value;
        }

    }

}
