//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.19 at 03:03:19 PM EDT 
//


package com.github.redhatqe.polarize.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for test-types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="test-types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="functional"/>
 *     &lt;enumeration value="non_functional"/>
 *     &lt;enumeration value="structural"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "test-types", namespace = "com.redhat.qe.rhsm.PolarizeTypes")
@XmlEnum
public enum TestTypes {

    @XmlEnumValue("functional")
    FUNCTIONAL("functional"),
    @XmlEnumValue("non_functional")
    NON_FUNCTIONAL("non_functional"),
    @XmlEnumValue("structural")
    STRUCTURAL("structural");
    private final String value;

    TestTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TestTypes fromValue(String v) {
        for (TestTypes c: TestTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
