//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.09 at 12:28:39 PM EDT 
//


package com.redhat.qe.rhsm.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for arch-types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="arch-types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="x8664"/>
 *     &lt;enumeration value="ppc64"/>
 *     &lt;enumeration value="ppc64le"/>
 *     &lt;enumeration value="ia64"/>
 *     &lt;enumeration value="aarch64"/>
 *     &lt;enumeration value="i386"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "arch-types", namespace = "com.redhat.qe.rhsm.PolarizeTypes")
@XmlEnum
public enum ArchTypes {

    @XmlEnumValue("x8664")
    X_8664("x8664"),
    @XmlEnumValue("ppc64")
    PPC_64("ppc64"),
    @XmlEnumValue("ppc64le")
    PPC_64_LE("ppc64le"),
    @XmlEnumValue("ia64")
    IA_64("ia64"),
    @XmlEnumValue("aarch64")
    AARCH_64("aarch64"),
    @XmlEnumValue("i386")
    I_386("i386");
    private final String value;

    ArchTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ArchTypes fromValue(String v) {
        for (ArchTypes c: ArchTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
