//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.18 at 01:45:10 PM EDT 
//


package com.redhat.qe.rhsm.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.redhat.qe.rhsm.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.redhat.qe.rhsm.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestCaseMetadata }
     * 
     */
    public TestCaseMetadata createTestCaseMetadata() {
        return new TestCaseMetadata();
    }

    /**
     * Create an instance of {@link Testcase }
     * 
     */
    public Testcase createTestcase() {
        return new Testcase();
    }

    /**
     * Create an instance of {@link ReqType }
     * 
     */
    public ReqType createReqType() {
        return new ReqType();
    }

    /**
     * Create an instance of {@link TeststepType }
     * 
     */
    public TeststepType createTeststepType() {
        return new TeststepType();
    }

    /**
     * Create an instance of {@link WorkItem }
     * 
     */
    public WorkItem createWorkItem() {
        return new WorkItem();
    }

    /**
     * Create an instance of {@link TestCaseMetadata.Workitems }
     * 
     */
    public TestCaseMetadata.Workitems createTestCaseMetadataWorkitems() {
        return new TestCaseMetadata.Workitems();
    }

    /**
     * Create an instance of {@link Testcase.Caseimportance }
     * 
     */
    public Testcase.Caseimportance createTestcaseCaseimportance() {
        return new Testcase.Caseimportance();
    }

    /**
     * Create an instance of {@link Testcase.Caselevel }
     * 
     */
    public Testcase.Caselevel createTestcaseCaselevel() {
        return new Testcase.Caselevel();
    }

    /**
     * Create an instance of {@link Testcase.Testtype }
     * 
     */
    public Testcase.Testtype createTestcaseTesttype() {
        return new Testcase.Testtype();
    }

    /**
     * Create an instance of {@link Testcase.Caseposneg }
     * 
     */
    public Testcase.Caseposneg createTestcaseCaseposneg() {
        return new Testcase.Caseposneg();
    }

    /**
     * Create an instance of {@link Testcase.Caseautomation }
     * 
     */
    public Testcase.Caseautomation createTestcaseCaseautomation() {
        return new Testcase.Caseautomation();
    }

    /**
     * Create an instance of {@link Testcase.Status }
     * 
     */
    public Testcase.Status createTestcaseStatus() {
        return new Testcase.Status();
    }

    /**
     * Create an instance of {@link Testcase.Requirements }
     * 
     */
    public Testcase.Requirements createTestcaseRequirements() {
        return new Testcase.Requirements();
    }

    /**
     * Create an instance of {@link Testcase.Teststeps }
     * 
     */
    public Testcase.Teststeps createTestcaseTeststeps() {
        return new Testcase.Teststeps();
    }

}
