//
// This file was originally generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation,
// v2.2.8-b130911.1802.  However it was customized to allow for namespaces to get their proper prefixes.  As such this
// this file will no longer be autogenerated when running gen-schema.sh
//

@javax.xml.bind.annotation.XmlSchema(
        namespace = "com.redhat.qe.rhsm.TestCaseType",
        elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
xmlns={ @javax.xml.bind.annotation.XmlNs(prefix = "pt", namespaceURI = "com.redhat.qe.rhsm.PolarizeTypes"),
        @javax.xml.bind.annotation.XmlNs(prefix= "tc", namespaceURI = "com.redhat.qe.rhsm.TestCaseType"),
        @javax.xml.bind.annotation.XmlNs(prefix = "req", namespaceURI = "com.redhat.qe.rhsm.RequirementType"),
        @javax.xml.bind.annotation.XmlNs(prefix="wit", namespaceURI = "com.redhat.qe.rhsm.WorkItemType")})
package com.redhat.qe.rhsm.schema;
