//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.07 at 03:18:06 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com.redhat.qe.rhsm.TestCaseType", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.redhat.qe.rhsm.schema;
