//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 08:29:01 AM EDT 
//


package com.redhat.qe.rhsm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="workitems">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="testcase" type="{}testcase-type"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="project-id" use="required" type="{}project-vals" />
 *       &lt;attribute name="dry-run" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "workitems"
})
@XmlRootElement(name = "TestCaseMetadata")
public class TestCaseMetadata {

    @XmlElement(required = true)
    protected TestCaseMetadata.Workitems workitems;
    @XmlAttribute(name = "project-id", required = true)
    protected ProjectVals projectId;
    @XmlAttribute(name = "dry-run")
    protected Boolean dryRun;

    /**
     * Gets the value of the workitems property.
     * 
     * @return
     *     possible object is
     *     {@link TestCaseMetadata.Workitems }
     *     
     */
    public TestCaseMetadata.Workitems getWorkitems() {
        return workitems;
    }

    /**
     * Sets the value of the workitems property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestCaseMetadata.Workitems }
     *     
     */
    public void setWorkitems(TestCaseMetadata.Workitems value) {
        this.workitems = value;
    }

    /**
     * Gets the value of the projectId property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectVals }
     *     
     */
    public ProjectVals getProjectId() {
        return projectId;
    }

    /**
     * Sets the value of the projectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectVals }
     *     
     */
    public void setProjectId(ProjectVals value) {
        this.projectId = value;
    }

    /**
     * Gets the value of the dryRun property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDryRun() {
        return dryRun;
    }

    /**
     * Sets the value of the dryRun property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDryRun(Boolean value) {
        this.dryRun = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="testcase" type="{}testcase-type"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "testcase"
    })
    public static class Workitems {

        @XmlElement(required = true)
        protected TestcaseType testcase;

        /**
         * Gets the value of the testcase property.
         * 
         * @return
         *     possible object is
         *     {@link TestcaseType }
         *     
         */
        public TestcaseType getTestcase() {
            return testcase;
        }

        /**
         * Sets the value of the testcase property.
         * 
         * @param value
         *     allowed object is
         *     {@link TestcaseType }
         *     
         */
        public void setTestcase(TestcaseType value) {
            this.testcase = value;
        }

    }

}
