//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 03:03:21 PM EDT 
//


package com.redhat.qe.rhsm.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for testcase-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testcase-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="caseimportance">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required" type="{}imp-types" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="caselevel">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required" type="{}case-types" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="testtype">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required" type="{}test-types" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="caseposneg">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required" type="{}posneg-types" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="caseautomation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" use="required" type="{}automation-types" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="status">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="requirement" type="{}req-type"/>
 *         &lt;element name="setup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="teststeps">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="teststep" type="{}teststep-type" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="teardown" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="author" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="workitem-type" use="required" type="{}wi-types" />
 *       &lt;attribute name="hyperlink" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="workitem-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="severity" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testcase-type", propOrder = {

})
public class TestcaseType {

    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected TestcaseType.Caseimportance caseimportance;
    @XmlElement(required = true)
    protected TestcaseType.Caselevel caselevel;
    @XmlElement(required = true)
    protected TestcaseType.Testtype testtype;
    @XmlElement(required = true)
    protected TestcaseType.Caseposneg caseposneg;
    @XmlElement(required = true)
    protected TestcaseType.Caseautomation caseautomation;
    @XmlElement(required = true)
    protected TestcaseType.Status status;
    @XmlElement(required = true)
    protected ReqType requirement;
    protected String setup;
    @XmlElement(required = true)
    protected TestcaseType.Teststeps teststeps;
    protected String teardown;
    @XmlAttribute(name = "author", required = true)
    protected String author;
    @XmlAttribute(name = "workitem-type", required = true)
    protected WiTypes workitemType;
    @XmlAttribute(name = "hyperlink")
    protected String hyperlink;
    @XmlAttribute(name = "workitem-id")
    protected String workitemId;
    @XmlAttribute(name = "severity")
    protected String severity;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the caseimportance property.
     * 
     * @return
     *     possible object is
     *     {@link TestcaseType.Caseimportance }
     *     
     */
    public TestcaseType.Caseimportance getCaseimportance() {
        return caseimportance;
    }

    /**
     * Sets the value of the caseimportance property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestcaseType.Caseimportance }
     *     
     */
    public void setCaseimportance(TestcaseType.Caseimportance value) {
        this.caseimportance = value;
    }

    /**
     * Gets the value of the caselevel property.
     * 
     * @return
     *     possible object is
     *     {@link TestcaseType.Caselevel }
     *     
     */
    public TestcaseType.Caselevel getCaselevel() {
        return caselevel;
    }

    /**
     * Sets the value of the caselevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestcaseType.Caselevel }
     *     
     */
    public void setCaselevel(TestcaseType.Caselevel value) {
        this.caselevel = value;
    }

    /**
     * Gets the value of the testtype property.
     * 
     * @return
     *     possible object is
     *     {@link TestcaseType.Testtype }
     *     
     */
    public TestcaseType.Testtype getTesttype() {
        return testtype;
    }

    /**
     * Sets the value of the testtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestcaseType.Testtype }
     *     
     */
    public void setTesttype(TestcaseType.Testtype value) {
        this.testtype = value;
    }

    /**
     * Gets the value of the caseposneg property.
     * 
     * @return
     *     possible object is
     *     {@link TestcaseType.Caseposneg }
     *     
     */
    public TestcaseType.Caseposneg getCaseposneg() {
        return caseposneg;
    }

    /**
     * Sets the value of the caseposneg property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestcaseType.Caseposneg }
     *     
     */
    public void setCaseposneg(TestcaseType.Caseposneg value) {
        this.caseposneg = value;
    }

    /**
     * Gets the value of the caseautomation property.
     * 
     * @return
     *     possible object is
     *     {@link TestcaseType.Caseautomation }
     *     
     */
    public TestcaseType.Caseautomation getCaseautomation() {
        return caseautomation;
    }

    /**
     * Sets the value of the caseautomation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestcaseType.Caseautomation }
     *     
     */
    public void setCaseautomation(TestcaseType.Caseautomation value) {
        this.caseautomation = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link TestcaseType.Status }
     *     
     */
    public TestcaseType.Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestcaseType.Status }
     *     
     */
    public void setStatus(TestcaseType.Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the requirement property.
     * 
     * @return
     *     possible object is
     *     {@link ReqType }
     *     
     */
    public ReqType getRequirement() {
        return requirement;
    }

    /**
     * Sets the value of the requirement property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReqType }
     *     
     */
    public void setRequirement(ReqType value) {
        this.requirement = value;
    }

    /**
     * Gets the value of the setup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSetup() {
        return setup;
    }

    /**
     * Sets the value of the setup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSetup(String value) {
        this.setup = value;
    }

    /**
     * Gets the value of the teststeps property.
     * 
     * @return
     *     possible object is
     *     {@link TestcaseType.Teststeps }
     *     
     */
    public TestcaseType.Teststeps getTeststeps() {
        return teststeps;
    }

    /**
     * Sets the value of the teststeps property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestcaseType.Teststeps }
     *     
     */
    public void setTeststeps(TestcaseType.Teststeps value) {
        this.teststeps = value;
    }

    /**
     * Gets the value of the teardown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeardown() {
        return teardown;
    }

    /**
     * Sets the value of the teardown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeardown(String value) {
        this.teardown = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the workitemType property.
     * 
     * @return
     *     possible object is
     *     {@link WiTypes }
     *     
     */
    public WiTypes getWorkitemType() {
        return workitemType;
    }

    /**
     * Sets the value of the workitemType property.
     * 
     * @param value
     *     allowed object is
     *     {@link WiTypes }
     *     
     */
    public void setWorkitemType(WiTypes value) {
        this.workitemType = value;
    }

    /**
     * Gets the value of the hyperlink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHyperlink() {
        return hyperlink;
    }

    /**
     * Sets the value of the hyperlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHyperlink(String value) {
        this.hyperlink = value;
    }

    /**
     * Gets the value of the workitemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkitemId() {
        return workitemId;
    }

    /**
     * Sets the value of the workitemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkitemId(String value) {
        this.workitemId = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeverity() {
        return severity;
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeverity(String value) {
        this.severity = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required" type="{}automation-types" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Caseautomation {

        @XmlAttribute(name = "value", required = true)
        protected AutomationTypes value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link AutomationTypes }
         *     
         */
        public AutomationTypes getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link AutomationTypes }
         *     
         */
        public void setValue(AutomationTypes value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required" type="{}imp-types" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Caseimportance {

        @XmlAttribute(name = "value", required = true)
        protected ImpTypes value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link ImpTypes }
         *     
         */
        public ImpTypes getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImpTypes }
         *     
         */
        public void setValue(ImpTypes value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required" type="{}case-types" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Caselevel {

        @XmlAttribute(name = "value", required = true)
        protected CaseTypes value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link CaseTypes }
         *     
         */
        public CaseTypes getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link CaseTypes }
         *     
         */
        public void setValue(CaseTypes value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required" type="{}posneg-types" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Caseposneg {

        @XmlAttribute(name = "value", required = true)
        protected PosnegTypes value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link PosnegTypes }
         *     
         */
        public PosnegTypes getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link PosnegTypes }
         *     
         */
        public void setValue(PosnegTypes value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Status {

        @XmlAttribute(name = "value")
        protected String value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="teststep" type="{}teststep-type" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "teststep"
    })
    public static class Teststeps {

        protected TeststepType teststep;

        /**
         * Gets the value of the teststep property.
         * 
         * @return
         *     possible object is
         *     {@link TeststepType }
         *     
         */
        public TeststepType getTeststep() {
            return teststep;
        }

        /**
         * Sets the value of the teststep property.
         * 
         * @param value
         *     allowed object is
         *     {@link TeststepType }
         *     
         */
        public void setTeststep(TeststepType value) {
            this.teststep = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="value" use="required" type="{}test-types" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Testtype {

        @XmlAttribute(name = "value", required = true)
        protected TestTypes value;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link TestTypes }
         *     
         */
        public TestTypes getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link TestTypes }
         *     
         */
        public void setValue(TestTypes value) {
            this.value = value;
        }

    }

}
