//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.30 at 02:05:36 PM EDT 
//


package com.redhat.qe.rhsm.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for variant-types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="variant-types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="server"/>
 *     &lt;enumeration value="client"/>
 *     &lt;enumeration value="workstation"/>
 *     &lt;enumeration value="computenode"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "variant-types")
@XmlEnum
public enum VariantTypes {

    @XmlEnumValue("server")
    SERVER("server"),
    @XmlEnumValue("client")
    CLIENT("client"),
    @XmlEnumValue("workstation")
    WORKSTATION("workstation"),
    @XmlEnumValue("computenode")
    COMPUTENODE("computenode");
    private final String value;

    VariantTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VariantTypes fromValue(String v) {
        for (VariantTypes c: VariantTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
