//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.08 at 08:21:22 AM EDT 
//


package com.github.redhatqe.polarize.importer.testcase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{}create"/>
 *           &lt;element ref="{}update"/>
 *         &lt;/choice>
 *         &lt;element ref="{}title"/>
 *         &lt;element ref="{}description"/>
 *         &lt;choice>
 *           &lt;element ref="{}functional"/>
 *           &lt;element ref="{}nonfunctional"/>
 *           &lt;element ref="{}structural"/>
 *         &lt;/choice>
 *         &lt;element ref="{}assignee" minOccurs="0"/>
 *         &lt;element ref="{}initial-estimate" minOccurs="0"/>
 *         &lt;element ref="{}tags" minOccurs="0"/>
 *         &lt;element ref="{}setup" minOccurs="0"/>
 *         &lt;element ref="{}test-steps" minOccurs="0"/>
 *         &lt;element ref="{}teardown" minOccurs="0"/>
 *         &lt;element ref="{}automation-script" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="level" default="component">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="component"/>
 *             &lt;enumeration value="integration"/>
 *             &lt;enumeration value="system"/>
 *             &lt;enumeration value="acceptance"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="posneg" default="positive">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="positive"/>
 *             &lt;enumeration value="negative"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="importance" default="medium">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="critical"/>
 *             &lt;enumeration value="high"/>
 *             &lt;enumeration value="medium"/>
 *             &lt;enumeration value="low"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="automation" default="notautomated">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="automated"/>
 *             &lt;enumeration value="notautomated"/>
 *             &lt;enumeration value="manualonly"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="component" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="subcomponent" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="upstream">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "create",
    "update",
    "title",
    "description",
    "functional",
    "nonfunctional",
    "structural",
    "assignee",
    "initialEstimate",
    "tags",
    "setup",
    "testSteps",
    "teardown",
    "automationScript"
})
@XmlRootElement(name = "testcase")
public class Testcase {

    protected Create create;
    protected Update update;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String description;
    protected Functional functional;
    protected Nonfunctional nonfunctional;
    protected Structural structural;
    protected String assignee;
    @XmlElement(name = "initial-estimate")
    protected String initialEstimate;
    protected String tags;
    protected String setup;
    @XmlElement(name = "test-steps")
    protected String testSteps;
    protected String teardown;
    @XmlElement(name = "automation-script")
    protected String automationScript;
    @XmlAttribute(name = "level")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String level;
    @XmlAttribute(name = "posneg")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String posneg;
    @XmlAttribute(name = "importance")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String importance;
    @XmlAttribute(name = "automation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String automation;
    @XmlAttribute(name = "component")
    @XmlSchemaType(name = "anySimpleType")
    protected String component;
    @XmlAttribute(name = "subcomponent")
    @XmlSchemaType(name = "anySimpleType")
    protected String subcomponent;
    @XmlAttribute(name = "upstream")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String upstream;

    /**
     * Gets the value of the create property.
     * 
     * @return
     *     possible object is
     *     {@link Create }
     *     
     */
    public Create getCreate() {
        return create;
    }

    /**
     * Sets the value of the create property.
     * 
     * @param value
     *     allowed object is
     *     {@link Create }
     *     
     */
    public void setCreate(Create value) {
        this.create = value;
    }

    /**
     * Gets the value of the update property.
     * 
     * @return
     *     possible object is
     *     {@link Update }
     *     
     */
    public Update getUpdate() {
        return update;
    }

    /**
     * Sets the value of the update property.
     * 
     * @param value
     *     allowed object is
     *     {@link Update }
     *     
     */
    public void setUpdate(Update value) {
        this.update = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the functional property.
     * 
     * @return
     *     possible object is
     *     {@link Functional }
     *     
     */
    public Functional getFunctional() {
        return functional;
    }

    /**
     * Sets the value of the functional property.
     * 
     * @param value
     *     allowed object is
     *     {@link Functional }
     *     
     */
    public void setFunctional(Functional value) {
        this.functional = value;
    }

    /**
     * Gets the value of the nonfunctional property.
     * 
     * @return
     *     possible object is
     *     {@link Nonfunctional }
     *     
     */
    public Nonfunctional getNonfunctional() {
        return nonfunctional;
    }

    /**
     * Sets the value of the nonfunctional property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nonfunctional }
     *     
     */
    public void setNonfunctional(Nonfunctional value) {
        this.nonfunctional = value;
    }

    /**
     * Gets the value of the structural property.
     * 
     * @return
     *     possible object is
     *     {@link Structural }
     *     
     */
    public Structural getStructural() {
        return structural;
    }

    /**
     * Sets the value of the structural property.
     * 
     * @param value
     *     allowed object is
     *     {@link Structural }
     *     
     */
    public void setStructural(Structural value) {
        this.structural = value;
    }

    /**
     * Gets the value of the assignee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignee() {
        return assignee;
    }

    /**
     * Sets the value of the assignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignee(String value) {
        this.assignee = value;
    }

    /**
     * Gets the value of the initialEstimate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialEstimate() {
        return initialEstimate;
    }

    /**
     * Sets the value of the initialEstimate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialEstimate(String value) {
        this.initialEstimate = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTags(String value) {
        this.tags = value;
    }

    /**
     * Gets the value of the setup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSetup() {
        return setup;
    }

    /**
     * Sets the value of the setup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSetup(String value) {
        this.setup = value;
    }

    /**
     * Gets the value of the testSteps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestSteps() {
        return testSteps;
    }

    /**
     * Sets the value of the testSteps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestSteps(String value) {
        this.testSteps = value;
    }

    /**
     * Gets the value of the teardown property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeardown() {
        return teardown;
    }

    /**
     * Sets the value of the teardown property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeardown(String value) {
        this.teardown = value;
    }

    /**
     * Gets the value of the automationScript property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutomationScript() {
        return automationScript;
    }

    /**
     * Sets the value of the automationScript property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutomationScript(String value) {
        this.automationScript = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel() {
        if (level == null) {
            return "component";
        } else {
            return level;
        }
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel(String value) {
        this.level = value;
    }

    /**
     * Gets the value of the posneg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosneg() {
        if (posneg == null) {
            return "positive";
        } else {
            return posneg;
        }
    }

    /**
     * Sets the value of the posneg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosneg(String value) {
        this.posneg = value;
    }

    /**
     * Gets the value of the importance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportance() {
        if (importance == null) {
            return "medium";
        } else {
            return importance;
        }
    }

    /**
     * Sets the value of the importance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportance(String value) {
        this.importance = value;
    }

    /**
     * Gets the value of the automation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutomation() {
        if (automation == null) {
            return "notautomated";
        } else {
            return automation;
        }
    }

    /**
     * Sets the value of the automation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutomation(String value) {
        this.automation = value;
    }

    /**
     * Gets the value of the component property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComponent() {
        return component;
    }

    /**
     * Sets the value of the component property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponent(String value) {
        this.component = value;
    }

    /**
     * Gets the value of the subcomponent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubcomponent() {
        return subcomponent;
    }

    /**
     * Sets the value of the subcomponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubcomponent(String value) {
        this.subcomponent = value;
    }

    /**
     * Gets the value of the upstream property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpstream() {
        return upstream;
    }

    /**
     * Sets the value of the upstream property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpstream(String value) {
        this.upstream = value;
    }

}
