//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.03 at 12:41:52 PM EDT 
//


package com.github.redhatqe.polarize.configuration;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for configType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="configType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="project-name" type="{}projectNameType"/>
 *         &lt;element name="basedir" type="{}basedir-Type" minOccurs="0"/>
 *         &lt;element name="requirements-xml" type="{}requirements-xmlType"/>
 *         &lt;element name="testcases-xml" type="{}testcases-xmlType"/>
 *         &lt;element name="mapping" type="{}mappingType"/>
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="project" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="servers" type="{}serversType"/>
 *         &lt;element name="importers" type="{}importersType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "config")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "configType", propOrder = {
    "projectName",
    "basedir",
    "requirementsXml",
    "testcasesXml",
    "mapping",
    "author",
    "project",
    "servers",
    "importers"
})
public class ConfigType {

    @XmlElement(name = "project-name", required = true)
    protected ProjectNameType projectName;
    protected BasedirType basedir;
    @XmlElement(name = "requirements-xml", required = true)
    protected RequirementsXmlType requirementsXml;
    @XmlElement(name = "testcases-xml", required = true)
    protected TestcasesXmlType testcasesXml;
    @XmlElement(required = true)
    protected MappingType mapping;
    @XmlElement(required = true)
    protected String author;
    @XmlElement(required = true)
    protected String project;
    @XmlElement(required = true)
    protected ServersType servers;
    @XmlElement(required = true)
    protected ImportersType importers;

    /**
     * Gets the value of the projectName property.
     * 
     * @return
     *     possible object is
     *     {@link ProjectNameType }
     *     
     */
    public ProjectNameType getProjectName() {
        return projectName;
    }

    /**
     * Sets the value of the projectName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProjectNameType }
     *     
     */
    public void setProjectName(ProjectNameType value) {
        this.projectName = value;
    }

    /**
     * Gets the value of the basedir property.
     * 
     * @return
     *     possible object is
     *     {@link BasedirType }
     *     
     */
    public BasedirType getBasedir() {
        return basedir;
    }

    /**
     * Sets the value of the basedir property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasedirType }
     *     
     */
    public void setBasedir(BasedirType value) {
        this.basedir = value;
    }

    /**
     * Gets the value of the requirementsXml property.
     * 
     * @return
     *     possible object is
     *     {@link RequirementsXmlType }
     *     
     */
    public RequirementsXmlType getRequirementsXml() {
        return requirementsXml;
    }

    /**
     * Sets the value of the requirementsXml property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequirementsXmlType }
     *     
     */
    public void setRequirementsXml(RequirementsXmlType value) {
        this.requirementsXml = value;
    }

    /**
     * Gets the value of the testcasesXml property.
     * 
     * @return
     *     possible object is
     *     {@link TestcasesXmlType }
     *     
     */
    public TestcasesXmlType getTestcasesXml() {
        return testcasesXml;
    }

    /**
     * Sets the value of the testcasesXml property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestcasesXmlType }
     *     
     */
    public void setTestcasesXml(TestcasesXmlType value) {
        this.testcasesXml = value;
    }

    /**
     * Gets the value of the mapping property.
     * 
     * @return
     *     possible object is
     *     {@link MappingType }
     *     
     */
    public MappingType getMapping() {
        return mapping;
    }

    /**
     * Sets the value of the mapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link MappingType }
     *     
     */
    public void setMapping(MappingType value) {
        this.mapping = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the project property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProject() {
        return project;
    }

    /**
     * Sets the value of the project property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProject(String value) {
        this.project = value;
    }

    /**
     * Gets the value of the servers property.
     * 
     * @return
     *     possible object is
     *     {@link ServersType }
     *     
     */
    public ServersType getServers() {
        return servers;
    }

    /**
     * Sets the value of the servers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServersType }
     *     
     */
    public void setServers(ServersType value) {
        this.servers = value;
    }

    /**
     * Gets the value of the importers property.
     * 
     * @return
     *     possible object is
     *     {@link ImportersType }
     *     
     */
    public ImportersType getImporters() {
        return importers;
    }

    /**
     * Sets the value of the importers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportersType }
     *     
     */
    public void setImporters(ImportersType value) {
        this.importers = value;
    }

}
