//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.16 at 03:55:25 PM EST 
//


package com.github.redhatqe.polarize.configuration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.redhatqe.polarize.configuration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Config_QNAME = new QName("", "config");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.redhatqe.polarize.configuration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConfigType }
     * 
     */
    public ConfigType createConfigType() {
        return new ConfigType();
    }

    /**
     * Create an instance of {@link TitleType }
     * 
     */
    public TitleType createTitleType() {
        return new TitleType();
    }

    /**
     * Create an instance of {@link JenkinsType }
     * 
     */
    public JenkinsType createJenkinsType() {
        return new JenkinsType();
    }

    /**
     * Create an instance of {@link EndpointType }
     * 
     */
    public EndpointType createEndpointType() {
        return new EndpointType();
    }

    /**
     * Create an instance of {@link TimeoutType }
     * 
     */
    public TimeoutType createTimeoutType() {
        return new TimeoutType();
    }

    /**
     * Create an instance of {@link ImporterType }
     * 
     */
    public ImporterType createImporterType() {
        return new ImporterType();
    }

    /**
     * Create an instance of {@link TemplateIdType }
     * 
     */
    public TemplateIdType createTemplateIdType() {
        return new TemplateIdType();
    }

    /**
     * Create an instance of {@link TestcasesXmlType }
     * 
     */
    public TestcasesXmlType createTestcasesXmlType() {
        return new TestcasesXmlType();
    }

    /**
     * Create an instance of {@link RequirementsXmlType }
     * 
     */
    public RequirementsXmlType createRequirementsXmlType() {
        return new RequirementsXmlType();
    }

    /**
     * Create an instance of {@link ProjectNameType }
     * 
     */
    public ProjectNameType createProjectNameType() {
        return new ProjectNameType();
    }

    /**
     * Create an instance of {@link TestSuiteType }
     * 
     */
    public TestSuiteType createTestSuiteType() {
        return new TestSuiteType();
    }

    /**
     * Create an instance of {@link CustomFieldsType }
     * 
     */
    public CustomFieldsType createCustomFieldsType() {
        return new CustomFieldsType();
    }

    /**
     * Create an instance of {@link MappingType }
     * 
     */
    public MappingType createMappingType() {
        return new MappingType();
    }

    /**
     * Create an instance of {@link ServerType }
     * 
     */
    public ServerType createServerType() {
        return new ServerType();
    }

    /**
     * Create an instance of {@link TestrunType }
     * 
     */
    public TestrunType createTestrunType() {
        return new TestrunType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link ImportersType }
     * 
     */
    public ImportersType createImportersType() {
        return new ImportersType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link SelectorType }
     * 
     */
    public SelectorType createSelectorType() {
        return new SelectorType();
    }

    /**
     * Create an instance of {@link BasedirType }
     * 
     */
    public BasedirType createBasedirType() {
        return new BasedirType();
    }

    /**
     * Create an instance of {@link ServersType }
     * 
     */
    public ServersType createServersType() {
        return new ServersType();
    }

    /**
     * Create an instance of {@link FileType }
     * 
     */
    public FileType createFileType() {
        return new FileType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "config")
    public JAXBElement<ConfigType> createConfig(ConfigType value) {
        return new JAXBElement<ConfigType>(_Config_QNAME, ConfigType.class, null, value);
    }

}
